routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('backend/app');
});

Route::resource('post', 'PostController');
Route::resource('user', 'UserController');
Route::get('send-email', 'UserController@sendMail');
Route::get('test-email', 'JobController@processQueue');
Route::get('test', 'MailController@index');
Route::resource('category', 'CategoryController');
Route::resource('product', 'ProductController');
Route::post('product/{product}/comment', 'CommentController@store')->name('product/comment');

app/Category.php
<?php

namespace App;

use App\Product;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = [];

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use Illuminate\Database\QueryException;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $serials = !is_null(request()->page) ? (request()->page-1) *20 : 0;
        $categories = Category::all();
        return view('backend.category.index', compact('categories','serials'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.category.create');
    }

    /**
     * 
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {

            Category::create($request->all());
            return redirect()->route('category.index');

        } catch (QueryException $e) {

            return redirect()->back();
        }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('backend.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $category->update($request->all());
        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->route('category.index');
    }
}

resources/views/backend/category/create.blade.php
@extends('backend.app')

@section('content')

<div class="container">
    <h4>Create Category</h4><br><br>

    <a href="{{ route('category.index') }}" class="btn btn-primary">Back</a>
    {!! Form::open
    (['route' => 'category.store',
    'method' => 'POST'])
    !!}

    <div class="form-group row">
        {!! Form::label('title','Title :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            {!! Form::text('title','', ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="form-group">
        {!! Form::submit('submit', ['class'=>'btn btn-success']) !!}
    </div>

    {!! Form::close() !!}



</div>

@endsection

resources/views/backend/category/edit.blade.php
@extends('backend.app')

@section('content')

<div class="container">
    <h4>Edit Category</h4><br><br>
    <a href="{{ route('category.index') }}" class="btn btn-primary">Back</a>

    {!! Form::model($category, 
    [
        'route' => ['category.update',$category->id],
        'method' => 'PUT',
    ]) !!}

    <div class="form-group row">
        {!! Form::label('title','Title :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            {!! Form::text('title',null, ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="form-group">
        {!! Form::submit('submit', ['class'=>'btn btn-success']) !!}
    </div>

    {!! Form::close() !!}



</div>

@endsection

resources/views/backend/category/index.blade.php
@extends('backend.app')

@section('content')
<div class="container mt-5">
    <br><h3>Category List</h3>
    <a href="{{ route('category.create') }}" class="btn btn-success">Create Category</a>
    

    <table class="table table-hover mt-1">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">title</th>
                <th scope="col">created</th>
                <th scope="col" class="row">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($categories as $category)
            <tr>
            <th scope="row">{{ ++$serials }}</th>
                <td>{{$category->title}}</td>
                <td>{{$category->created_at}}</td>
                <td class="row">
                    <a href="{{ route('category.edit', $category->id) }}" class="btn btn-warning">Edit</a>
                    <form action="{{ route('category.destroy',$category->id) }}" method="post" class="">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection