routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('backend/app');
});

Route::resource('post', 'PostController');
Route::resource('user', 'UserController');
Route::get('send-email', 'UserController@sendMail');
Route::get('test-email', 'JobController@processQueue');
Route::get('test', 'MailController@index');
Route::resource('category', 'CategoryController');
Route::resource('product', 'ProductController');
Route::post('product/{product}/comment', 'CommentController@store')->name('product/comment');

app/Product.php
<?php

namespace App;

use App\Comment;
use App\Category;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $guarded = [];

    public function category()
        {
            return $this->belongsTo(Category::class);
        }
    
    public function comments()
    {
        return $this->morphMany('App\Comment','commentable');
    }
   
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Product;
use App\Category;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $serials = !is_null(request()->page) ? (request()->page-1) * 20 : 0;
        $products = Product::all();
        return view('backend.product.index', compact('products','serials'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        $categories = Category::pluck('title','id')->toArray();
        return view('backend.product.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $data = $request->all();
        $products = Product::create($data);
        return redirect()->route('product.index');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $products = Product::findOrFail($id);
        $categories = Category::pluck('title','id');
        return view('backend.product.show',compact('products','categories'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::findOrfail($id);
        $categories = Category::pluck('title','id');
        return view('backend.product.edit',compact('product','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $product->update($request->all());
        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::findOrfail($id)->delete();
        
        return redirect()->route('product.index');
    }
}

resources/views/backend/product/create.blade.php
@extends('backend.app')

@section('content')

<div class="container">
    <h4>Create Product</h4><br><br>
    <a href="{{ route('product.index') }}" class="btn btn-primary">Back</a>

    {!! Form::open
    (['route' => 'product.store',
    'method' => 'POST'])
    !!}

    <div class="form-group row">
        {!! Form::label('title','Title :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            {!! Form::text('title','', ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="form-group row">
        {!! Form::label('category_id','Category :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            <select class="custom-select" id="inputGroupSelect01" name="category_id">
                <option selected>Choose One Category ...</option>
                @foreach ($categories as $key => $category)
                <option value="{{ $key }}">{{ $category }}</option>
                @endforeach
            </select>
        </div>
    </div>
    <div class="form-group row">
        {!! Form::label('description','Description :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            {!! Form::textarea('description','', ['class'=>'form-control' ,'rows'=>'3']) !!}
        </div>
    </div>
    <div class="form-group row">
        {!! Form::label('prize','Prize :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            {!! Form::text('prize','', ['class'=>'form-control']) !!}
        </div>
    </div>
    {{-- <div class="form-group row">
        {!! Form::label('image','Picture :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            {!! Form::file('image', $images, ['class' => 'form-control']); !!}
        </div>
    </div> --}}

    {{-- <div class="form-group row">
        {!! Form::label('comment','Comment :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            {!! Form::textarea('comment',null, ['class'=>'form-control','rows'=>'3']) !!}
        </div>
    </div> --}}
   

    <div class="form-group">
        {!! Form::submit('submit', ['class'=>'btn btn-success']) !!}
    </div>

    {!! Form::close() !!}



</div>

@endsection

resources/views/backend/product/edit.blade.php
@extends('backend.app')

@section('content')

<div class="container">
    <h4>Edit Product</h4><br><br>
    <a href="{{ route('product.index') }}" class="btn btn-primary">Back</a>

    {!! Form::model($product, 
    [
        'route' => ['product.update',$product->id],
        'method' => 'PUT',
    ]) !!}

    <div class="form-group row">
        {!! Form::label('title','Title :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            {!! Form::text('title',null, ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="form-group row">
        {!! Form::label('category_id','Category :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            <select class="custom-select" id="inputGroupSelect01" name="category_id">
                <option selected>{{$product->category->title}}</option>
                @foreach ($categories as $key => $category)
                <option value="{{ $key }}">{{ $category }}</option>
                @endforeach
            </select>
        </div>
    </div>
    <div class="form-group row">
        {!! Form::label('description','Description :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            {!! Form::text('description',null, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="form-group row">
        {!! Form::label('prize','Prize :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            {!! Form::text('prize',null, ['class' => 'form-control']) !!}
        </div>
    </div>


    <div class="form-group">
        {!! Form::submit('submit', ['class'=>'btn btn-success']) !!}
    </div>

    {!! Form::close() !!}



</div>

@endsection

resources/views/backend/product/index.blade.php
@extends('backend.app')

@section('content')
<div class="container mt-5">
    <br><h3>Product List</h3>
    <a href="{{ route('product.create') }}" class="btn btn-success">Create Product</a>

    <table class="table table-hover mt-1">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">title</th>
                <th scope="col">Category</th>
                <th scope="col">Description</th>
                <th scope="col">Prize</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($products as $product)
            <tr>
            <th scope="row">{{ ++$serials }}</th>
                <td>{{$product->title}}</td>
                <td>{{ $product->category->title }}</td>
                <td>{{ $product->description}}</td>
                <td>{{ $product->prize}}</td>
                <td class="row">
                    <a href="{{ route('product.show', $product->id) }}" class="btn btn-primary">Show</a>
                    <a href="{{ route('product.edit',$product->id) }}" class="btn btn-success">Edit</a>
                    <form action="{{ route('product.destroy',$product->id) }}" method="post">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection

resources/views/backend/product/show.blade.php
@extends('backend.app')

@section('content')
<div class="container mt-5">
    <br>
    <h3>Product List</h3>
    <a href="{{ route('product.index') }}" class="btn btn-success mb-2">Back To Product List</a>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">title</th>
                <th scope="col">Category</th>
                <th scope="col">Description</th>
                <th scope="col">Prize</th>
                <th scope="col">
                    @if(count($products->comments) > 0)
                    <p class="">Comments <span class="badge badge-primary">{{count($products->comments)}}</span></p>
                    
                    @else
                    <p>Comment</p>
                    @endif
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{$products->title}}</td>
                <td>{{ $products->category->title }}</td>
                <td>{{ $products->description}}</td>
                <td>{{ $products->prize}}</td>
                <td>
                    <ul>
                        @foreach($products->comments as $comment)
                        <li>
                            {{$comment->body}}
                            <small>
                                {{$comment->created_at->diffForHumans()}}
                                <mark>{{$comment->created_at->toFormattedDateString()}}</mark>
                            </small>
                        </li>
                        @endforeach
                    </ul>


                </td>
            </tr>

        </tbody>
    </table>
    {{-- comment box --}}
    <form action="{{route('product/comment',$products->id)}}" method="post" style="width:
        100%">
        @csrf
        <div class="form-group">
            <label for="comment">Comment</label>
            <textarea rows="3" class="form-control" id="comment" name="comment"></textarea>
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
</div>
@endsection