routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('backend/app');
});

Route::resource('post', 'PostController');
Route::resource('user', 'UserController');
Route::get('send-email', 'UserController@sendMail');
Route::get('test-email', 'JobController@processQueue');
Route::get('test', 'MailController@index');
Route::resource('category', 'CategoryController');
Route::resource('product', 'ProductController');
Route::post('product/{product}/comment', 'CommentController@store')->name('product/comment');

app/User.php
<?php

namespace App;

use App\Image;
use App\Profile;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    
    public function profile()
    {
        return $this->hasOne(Profile::class );
    }
    

    public function image(){

        return $this->morphOne('App\Image', 'imageable');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Profile;
use App\Mail\SendMail;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::all();
        // dd($user);
        return view('backend.user.index', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(user $user)
    {
        return view('backend.user.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        $profile = Profile::pluck('bio','facebook_url');

        return view('backend.user.edit', compact('user','profile'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    
    public function update(Request $request, user $user)
    {
        
        $userData = $request->only('name');
        $profileData = $request->only('bio','address','facebook_url');
        
        $user->update($userData);
        $user->profile()->update($profileData);
        
        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    // email send 

    public function sendMail(){

        $to_email = 'kmahim489@gmail.com';

        Mail::to($to_email)->send(new SendMail);
        
        
        return "E-mail has been sent successfully";
    }
}

resources/views/backend/user/edit.blade.php
@extends('welcome')

@section('content')

<div class="container">
    <h4>Edit User</h4><br><br>

    <a href="{{ route('user.index') }}" class="btn btn-primary">Back</a>
    {!! Form::model($user,[
    'route' => ['user.update', $user->id],
    'method' => 'PUT'])
    !!}

    <div class="form-group row">
        {!! Form::label('name','Name :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            {!! Form::text('name',null, ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="form-group row">
        {!! Form::label('email','Email :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            {!! Form::text('email',null, ['class'=>'form-control']) !!}
        </div>
    </div>
    <div class="form-group row">
        {!! Form::label('bio','Bio :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            {!! Form::textarea('bio',$user->profile->bio, ['class'=>'form-control','rows'=>'3']) !!}
        </div>
    </div>
    <div class="form-group row">
        {!! Form::label('facebook_url','Facebook :' ,['class' => 'col-sm-2 col-form-label']) !!}
        <div class="col-sm-10">
            {!! Form::text('facebook_url',$user->profile->facebook_url, ['class'=>'form-control']) !!}
        </div>
    </div>
    
    <div class="form-group">
        {!! Form::submit('Update', ['class'=>'btn btn-success']) !!}
    </div>

    {!! Form::close() !!}



</div>

@endsection

resources/views/backend/user/index.blade.php
@extends('welcome')

@section('content')
<div class="container">
    <h3>All User Here</h3><br><br>
    {{-- <a href="{{ route('user.create') }}" class="btn btn-success">Create Post</a> --}}
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Body</th>
                <th scope="col">Bio</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($user as $singleUser)
            <tr>
                <th scope="row">1</th>
                <td>{{ $singleUser->name }}</td>
                <td>{{ $singleUser->email }}</td>
                <td>{{$singleUser->profile->bio}}</td>
                <td>
                    <a href="{{ route('user.show', $singleUser->id) }}" class="btn btn-primary">Show</a>
                    <a href="{{ route('user.edit', $singleUser->id) }}" class="btn btn-warning">Edit</a>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection

resources/views/backend/user/show.blade.php
@extends('welcome')

@section('content')
<div class="container">
    <h3>All User Here</h3><br><br>
    <a href="{{ route('user.index') }}" class="btn btn-outline-primary">Back</a>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Body</th>
                <th scope="col">Bio</th>
                <th scope="col">Facebook</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{$user->profile->bio}}</td>
                <td>{{$user->profile->facebook_url}}</td>
            </tr>
        </tbody>
    </table>
</div>
@endsection